### ISSUE TITLE
Modify auto-scaling criteria

### ISSUE THREAD

**Issue by Hainish** [EFForg/phantom-of-the-capitol#60]
Deployment (not project) task:

Currently, our auto-scaling is set up to be quick to scale up after seeing a memory spike, and quick to scale down after seeing that memory spike go below a threshold.  I think it would be better to be easy to scale up, but stay up for some number of hours after we pass under the threshold again.  This way, when the threshold is constantly being crossed on big days of action, we won't be constantly spinning up and then down instances.

@j-ro @apechimp I'd love your input here. I think it would be interesting to see the deployment strategies for congress-forms across the board, and share things like metrics for scaling. It seems it would be in everyones interest who runs CF to be involved in discussions of these types, for us to optimize the durability of our instances.  I wonder what the best forum for this is: a mailing list?

**Comment by Hainish** [comment]
We currently have one mailing list for contact-congress, but that's more generic I think than the problems specific to CF.

**Comment by Hainish** [comment]
cc @rubbingalcoholic @ChrisAntaki

**Comment by j-ro** [comment]
We're running 10 instances behind a load balancer for form filling, plus one instance that only serves the contact forms to users so they can fill it out, and one instance that only does captchas. We're not doing any autoscaling at this point, as all of these instances can run fine on a single AWS server we've got. The one part of this I'm nervous about is the captchas, since they take so long to process with all the round trips to the user, but since there are so few forms with captchas (and it seems less every day) so far it hasn't been a big issue.

**Comment by Hainish** [comment]
@j-ro so you're using the `DELAY_ALL_NONCAPTCHA_FILLS` env, and processing the jobs with the rake tasks later?

Wow, 10 instances!  Is that the # of processes for the request handler or 10 actual separate CF apps running?  I'm guessing the first, since you said you have a single AWS server.  Or are they running on separate VMs?

**Comment by j-ro** [comment]
No, I think we're queuing the processes in our Ruby app and sending them over that way. We do use the rake tasks, but that's for refilling broken forms after they're fixed (some of them can then be successfully delivered).

I believe we're running 10 separate apps, but not 100% sure. @gcosta, want to weigh in?

**Comment by apechimp** [comment]
I'm no longer familiar with NGP VAN's implementation @bwestergard or @kthayer424 may be.
