### ISSUE TITLE
Concurrent Connection Limits

### ISSUE THREAD

**Issue by tech-workwithiws** [EFForg/phantom-of-the-capitol#71]
We have installed this API and are successfully submitting letters at a rate of about 5K per day.   However, ideally we are looking for a solution that is capable of sending significantly more than this.  I believe that the limitation we're encountering is related to PhantomJS and its ability to process concurrent connections.

Can you tell us if the approximately 5K per day limit is typical?  If so, are there suggestions as to how we can architect a solution that can exceed this?  I assume multiple virtual servers running separate instances is one/costly option...Is it possible to install multiple instances of Phantom of the Capital on the same server, each listening on a different port, so that a single server would be capable of exceeding this limit?

Thanks

**Comment by j-ro** [comment]
I believe we use multiple instances/ports, yep. We run over 10 instances, and submit many tens of thousands per day.

**Comment by j-ro** [comment]
I would also say, 5k/day seems slow. For us, forms submit within about 10 seconds, and usually faster than that, so I'd say we hit 10k/day/instance pretty easily.

**Comment by tech-workwithiws** [comment]
Thanks for your prompt response!  5K was a low estimate.  We're actually running 6 per minute, which works out to closer to 9K...Seems to be inline with what you're reporting, as well.

Can you provide any guidance on how to run multiple instances?  Is it as easy as editing Vagrantfile with a free port, running rackup, and then repeating the process?

**Comment by j-ro** [comment]
I'll be honest that I don't know exactly how it was set up. My sense is we've got it behind a load balancer of some sort. But we're definitely connecting over a few ports.

**Comment by Hainish** [comment]
@tech-workwithiws there is a mailing list for orgs that have deployed Phantom-DC, this question is probably more appropriate there.  If you want me to add you, email me at bill@eff.org.

We haven't really done much load testing with remote forms in the past, partly because until recently `phantom-dc` was tightly bound to the `contact-congress` data source, and we don't want to spam congress in order to load test our application.  Recent changes have abstracted the concept of a `data-source`, of which `contact-congress` can be one of many.  So we might want to do some load testing with some `data-source` we create ourselves that can hammer on.  There is some really limited load tests in the testing suite, but they aren't really made to account for production scenarios.

Instead of using separate virtual instances (one per phantom-dc server) for this, a more cost-effective way to handle the load may be to spin up multiple instances using docker on a CoreOS cluster.  Containers are much more light-weight than VMs, and scaling up can happen almost instantaneously, which is nice in those high-traffic scenarios.  I have a Dockerfile in the project, and I'll be adding more documentation on how to use it soon.
