### ISSUE TITLE
Integrating the House CWC API?

### ISSUE THREAD

**Issue by sinak** [EFForg/phantom-of-the-capitol#79]
Hey everyone, 

@joelcollinsdc let me know a few weeks back that the House has released [its application](http://www.house.gov/content/vendors/cwc/) for the Communicating with Congress (CWC) API. I just checked in and Joel reports that half the House are signed up to use it. 

I'm wondering whether we should consider integrating CWC into phantom-dc. I have the full API spec and am waiting to hear back on whether I'm allowed to post it publicly. If I am, I'll update this post. But basically its an XML based API, and while its relatively complicated, a lot of the fields are optional.

Some thoughts on my end:
- CWC is only intended for "mass communications" not authentic constituent messages. We should perhaps only have it as an optional delivery method, otherwise authentic constituent messages won't make it through.
- That means that if we do implement the API, we'll still need to maintain YAML files for the most part.
- The main advantages would be quicker delivery (API is faster than using a headless browser), and fewer CAPTCHAs for end-users submitting bulk messages.

Curious as to other's thoughts.

**Comment by j-ro** [comment]
My vote is that this isn't appropriate for this project. I think this project has a specific purpose -- to fill out forms on the web via YAML (whether they be congress or something else -- we already do state level, and may get into government agencies at some point).

If Congress comes up with an API to submit communications that's great -- I hope it sees adoption. But I think integrating with it should be a different project (or just a function of the app that each of us builds that uses phantom-of-the-capitol to deliver YAML communications). For example, where we have email addresses (and we do for a lot at the state level), we deliver those outside of phantom. Where we need to use contact forms, we use phantom. Same thing here in my mind -- if you want to use this API, where available you can use a different app to do it, and where contact forms are necessary, you use this.

**Comment by Hainish** [comment]
@sinak @j-ro I'm undecided on this.  It's an interesting concept to separate out the API for mass communications, but it looks like there is no open enrollment for this - you have to get approved, and who knows what kind of agreement you need to comply with to be accepted.  I doubt any piece of middleware will actually be needed for this to work, since it seems like CWC itself has an API ready to use by the front-end application.  I'd like more info on this before deciding how to proceed.

**Comment by joelcollinsdc** [comment]
Thanks everyone.  I would agree that since the CWC use case is only one of the supported use cases of this project it may not make sense to include it here, save perhaps for a note on the documentation about related APIs.  For those who may be interested, CWC does offer some potential benefits like a standardized issue list and the ability to associate each message with a bill which will hopefully allow Members to more easily aggregate their constituents sentiments.

**Comment by j-ro** [comment]
done!
