### ISSUE TITLE
Upgrade to SHA2 SSL Certificates

### ISSUE THREAD

**Issue by GedLawrenson** [EFForg/phantom-of-the-capitol#83]
Hi,

The production site (https://congressforms.eff.org/) is currently using a weak SHA1 certificate. This needs to be updated to SHA2, and Google Chrome is now reporting the site as 'neutral' rather than 'secure'.

This is my first contribution to phantom, is anyone here in control of the production service?

**Comment by j-ro** [comment]
There's not really a production service, at least officially. That setup there may just be a demo. But @Hainish would be the person to fix it anyway.

**Comment by TheNotary** [comment]
Thanks for contributing GedLawrenson!  

A fix for this is in the pipeline, but it's a more involved process due to the number of sites we're juggling with 3rd party contract signers and the fact that most of EFF's techs are distracted, at the edge of our seats, waiting in anticipation to hear the next thing T-Mobile CEO curses into his webcam surrounding his company's latest data throttling trick.  Why can't they just focus on making cheaper, less track capable burners like in the old days?

Regards!

**Comment by Hainish** [comment]
I'm seeing a sha2 cert, so closing this.  If you're still seeing sha-1, you may be encountering the cert chain building bug in NSS, see details here: https://sslmate.com/blog/post/chrome_cached_sha1_chains
